### PR TITLE
Mention "political views" in Code of Conduct

### PR DESCRIPTION
**Pull request by bih**

### CODE REVIEW

**Comment by cbetta** [comment]
I like this, but I wonder if this leaves it open for extremists to try and protect their actions. Any thoughts on that?

**Comment by bih** [comment]
It is a good point. I would also recommend updating the initial sentence to mention:

> Our hackathon is dedicated to providing a __safe and comfortable environment and__ harassment-free experience for everyone, regardless of the following:

Maybe I have a incomplete view on this, and this is perfect for getting the opinions of yourself and other organizers on this, but in my experience, folks who have extremist actions are likely to also either a) fit in other CoC-breaking actions or b) make a number of people feel unsafe or uncomfortable.

**Comment by cbetta** [comment]
Agreed. Can you make that additional change so I can merge it?

**Comment by bih** [comment]
Updated 👍

**Pull request merged**
